pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    def mavenHome = tool 'Maven 3.9.0'
                    env.PATH = "${mavenHome}/bin:${env.PATH}"
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    def mavenHome = tool 'Maven 3.9.0'
                    env.PATH = "${mavenHome}/bin:${env.PATH}"

                    try {
                        sh 'mvn test'
                    } catch (Exception e) {
                        currentBuild.result = 'UNSTABLE'
                        throw e
                    } finally {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }

        stage('Deliver') {
            steps {
                script {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
