pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('src') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('src') {
                    try {
                        sh 'mvn test'
                    } catch (Exception e) {
                        currentBuild.result = 'UNSTABLE'
                        throw e
                    } finally {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
